# .github/workflows/ci-cd.yml

name: hello-world

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Hello World
      run: |
        chmod +x hello-world.sh
        ./hello-world.sh

