name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create file
      run: |
        echo "This is a M Ahmad Saeed." > ahmad.txt

    - name: Copy file to local machine
      run: |
        cp generated_file.txt /home/ahmad/mysite/hello-world-cicd

    - name: Display file content
      run: |
        cat generated_file.txt
