name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.G_ACTION }}

    - name: Create file
      run: |
        echo "This is a generated file." > generated_file.txt

    - name: Copy file to local machine
      run: |
        scp -o StrictHostKeyChecking=no -P 22 generated_file.txt ahmad@192.168.26.129:/home/github_action
      # Note: Replace 'ahmad', '192.168.26.129', and '/home/github_action' with your actual SSH username, Ubuntu machine IP, and the desired destination path.

    - name: Display file content
      run: |
        cat generated_file.txt
